language: c

os:
  - osx

before_install:
  - brew update

install:
  # Don't re-clone, inspired by
  # https://github.com/neovim/homebrew-neovim/blob/master/.travis.yml
  - mkdir -p $(brew --repo)/Library/Taps/tavianator
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/tavianator/homebrew-tap

script:
  - brew install tavianator/tap/bfs
  - brew audit bfs --strict
  # See https://github.com/Homebrew/brew/issues/6019
  - HOMEBREW_NO_SANDBOX=1 brew test -v bfs
  - bfs --version
