name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install coreutils

      - name: Link repo
        run: |
          # Don't re-clone, inspired by
          # https://github.com/neovim/homebrew-neovim/blob/master/.travis.yml
          mkdir -p $(brew --repo)/Library/Taps/tavianator
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/tavianator/homebrew-tap

      - name: Install formula
        run: |
          brew install tavianator/tap/bfs

      - name: Run tests
        run: |
          brew audit bfs --strict
          # Run this outside the sandbox, see https://github.com/Homebrew/brew/issues/6019
          cd /usr/local/Cellar/bfs/*/share/bfs
          ./tests.sh --bfs=bfs --verbose
