name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install coreutils

      - name: Link repo
        run: |
          # Don't re-clone, inspired by
          # https://github.com/neovim/homebrew-neovim/blob/master/.travis.yml
          mkdir -p $(brew --repo)/Library/Taps/tavianator
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/tavianator/homebrew-tap

      - name: Install formula
        run: |
          brew install tavianator/tap/bfs

      - name: Run tests
        run: |
          brew audit bfs --strict
          # Run this outside the sandbox, see https://github.com/Homebrew/brew/issues/6019
          git clone -b "$(bfs --version | sed -n 's/bfs //p')" https://github.com/tavianator/bfs
          make -C bfs -j$(sysctl -n hw.ncpu) bin/tests/mksock
          # Work around https://github.com/actions/runner/issues/884
          genv --default-signal=PIPE ./bfs/tests/tests.sh --bfs=bfs --sudo --verbose=skipped
